spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID} # 구글 API콘솔로 발급받은 ID
            clientSecret: ${G_CLIENT_SECRET} # 구글 API콘솔로 발급받은 SECRET
            scope:
              - email
              - profile
          github:
            clientId: ${H_CLIENT_ID}
            clientSecret: ${H_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # == http://localhost:8080/login/oauth2/code/github)
            authorization-grant-type: authorization_code
            client-name: GitHub
            scope:
              - user
              - repo
          kakao:
            client-id: ${K_CLIENT_ID} # 앱 설정 -> 앱 키 -> REST API 키
            client-secret: ${K_CLIENT_SECRET}  # 제품 설정 -> 카카오 로그인 -> 보안 -> Client Secret
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # == http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-id: ${N_CLIENT_ID}
            client-secret: ${N_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true

jwt:
  secret-key: ${JWT_SECRET_KEY}  # 환경 변수로 설정했음
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420